name: Secrets and Environment Variables

on:
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest
    env:
      MY_APP_ID: ${{ vars.APP_ID }}

    steps:

      - name: Tell me a secret!
        run: echo "My existing secret is ${{ secrets.RESOURCE_ZIPPER }}"
      
      
