name: Secrets and Environment Variables

on:
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest
    env:
      MY_APP_ID: ${{ vars.APP_ID }}

    steps:

      - name: Tell me a secret!
        run: echo "My existing secret is ${{ secrets.RESOURCE_ZIPPER }}"
      
      - uses: actions/checkout@v2
      - name: Read the env from an external script
        run: |
         chmod +x .github/scripts/custom.sh
         .github/scripts/custom.sh
        shell: bash
  
  top-secret-production:
    runs-on: ubuntu-latest
    environment: production
    env:
      APP_ID: ${{ vars.APP_ID }}

    steps:
      - name: Read a variable
        run: echo "My APP_ID value in the production job is $APP_ID"
