name: Update Resource Pack

on:
  push:
    branches:
      - main  # Adjust the branch name if needed
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create ZIP file
        run: zip -r resource-pack.zip https://www.dropbox.com/scl/fo/vg5bxpcpklxlgc5wx0k4w/h?rlkey=hhs1mf0crvmmk1tj41qd7o8rf&dl=0

      - name: Upload ZIP to web server
        uses: actions/upload-artifact@v2
        with:
          name: resource-pack
          path: resource-pack.zip
